import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import Banner from "@/components/Banner";
import Services from "@/components/Services";
import Questions from "@/components/Questions";
import Works from "@/components/Works";
import Sqhema from "@/components/Sqhema";
import InCost from "@/components/InCost";
import Reviews from "@/components/Reviews";
import Tinkoff from "@/components/Tinkoff";
import Types from "@/components/Types";
import Experiense from "@/components/Experiense";
import Equipment from "@/components/Equipment";
import KnowCost from "@/components/KnowCost";

export default function Home() {
  return (
    <>
      <Head>
        <title>Бурение скважин на воду в Челябинске</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Header />
        <Banner />
        <Services />
        <Works />
        <Tinkoff />
        <Types />
        <Experiense />
        <Equipment />
        <KnowCost />
        <Reviews />
        <InCost />
        <Sqhema />
        <Questions />
      </main>
    </>
  );
}
